# Generated by Django 2.2 on 2020-03-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Address',
            new_name='address',
        ),
    ]
