# Generated by Django 2.2 on 2020-03-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20200316_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='id',
        ),
        migrations.AlterField(
            model_name='form',
            name='rollnumber',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
