# Generated by Django 2.2 on 2020-09-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_table',
            name='customer_name',
        ),
    ]
