# Generated by Django 2.2 on 2020-09-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_customer_table_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_table',
            name='customer_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customer_table',
            name='ezzy_id',
            field=models.IntegerField(default=0),
        ),
    ]
