# Generated by Django 2.2 on 2020-09-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200924_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_table',
            name='ezzy_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message_forwarding_log',
            name='scheduler_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduler_table',
            name='scheduler_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template_table',
            name='template_id',
            field=models.IntegerField(default=0),
        ),
    ]
