# Generated by Django 2.2 on 2020-10-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_scheduler_table_scheduler_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler_table',
            name='scheduler_id',
            field=models.IntegerField(default=0),
        ),
    ]
