# Generated by Django 2.2 on 2020-10-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_scheduler_table_scheduler_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler_table',
            name='scheduler_id',
            field=models.CharField(max_length=100),
        ),
    ]
