# Generated by Django 2.2 on 2020-10-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20201003_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_table',
            name='ezzy_id',
            field=models.CharField(max_length=100),
        ),
    ]
