# Generated by Django 2.2 on 2020-10-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20201004_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_table',
            name='opt_out_template_status',
            field=models.BooleanField(default=False),
        ),
    ]
