# Generated by Django 2.2 on 2020-03-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymaster',
            name='cid',
            field=models.IntegerField(default=True),
        ),
    ]
