# Generated by Django 2.2 on 2020-02-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_auto_20200213_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
