# Generated by Django 3.1.3 on 2020-12-28 18:00

from django.db import migrations, models
import practice1.manager


class Migration(migrations.Migration):

    dependencies = [
        ('practice1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('object', practice1.manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
