# Generated by Django 2.2 on 2020-03-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='chk',
            field=models.BooleanField(default=False),
        ),
    ]
