# Generated by Django 2.2 on 2020-03-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_chk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='chk',
            field=models.BooleanField(default=True),
        ),
    ]
