# Generated by Django 2.2 on 2020-03-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200308_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='chk',
        ),
    ]
