# Generated by Django 2.2 on 2020-09-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('rollno', models.IntegerField(max_length=10)),
                ('school_name', models.CharField(default='', max_length=20)),
                ('phoneno', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
