# Generated by Django 2.2 on 2020-02-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=30)),
                ('studentroll', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('studentimage', models.ImageField(default='', upload_to='image')),
            ],
        ),
    ]
